// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3FIAlGafpuI5a875hT_89BhUSjTjZq3M',
    appId: '1:678791692736:web:3c9b2e08120b6ad23f8825',
    messagingSenderId: '678791692736',
    projectId: 'tugas-akhir-e1997',
    authDomain: 'tugas-akhir-e1997.firebaseapp.com',
    storageBucket: 'tugas-akhir-e1997.appspot.com',
    measurementId: 'G-J7KXQ812QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFtfer8SK29XcMxELsJk1LP4xQYUuYCdo',
    appId: '1:678791692736:android:0c9c03ecb1f759723f8825',
    messagingSenderId: '678791692736',
    projectId: 'tugas-akhir-e1997',
    storageBucket: 'tugas-akhir-e1997.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnRcCnQfpFlJtSV6yvZut4BMoO_GAxZCI',
    appId: '1:678791692736:ios:61f2d66b3f6b88a03f8825',
    messagingSenderId: '678791692736',
    projectId: 'tugas-akhir-e1997',
    storageBucket: 'tugas-akhir-e1997.appspot.com',
    iosClientId: '678791692736-va6kmlnlp3jgkmgi4jq369263a1c2kk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectTugasAkhir',
  );
}
